openapi: 3.1.0
info:
  title: Trading Assistant API (Canonical + Diag)
  version: "1.0.0"
servers:
  - url: https://tradingassistantmcpready-production.up.railway.app
    description: Production
components:
  schemas:
    StdEnvelope:
      type: object
      required: [status]
      properties:
        status: { type: string, enum: [ok, error] }
        data: {}
        error: { type: string, nullable: true }
paths: {}
